name: Test Cache

on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk

env:
  IMAGE_NAME: jass-duckie-town-webservice

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    env:
      DOCKER_TARGET_PLATFORM: linux/arm64/v8

    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile2
          platforms: linux/arm64/v8
          push: false
          tags: jass-duckie-town-webservice
          labels: "runnumber=${GITHUB_RUN_ID}"
          load: true
          build-args: |
            ARCH=arm64
            TOKEN=${{ secrets.CACHE_TOKEN }}
